"""add_profile_fields

Revision ID: b785c678f512
Revises: e27aafd466ef
Create Date: 2026-07-12 06:09:07.092135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b785c678f512'
down_revision: Union[str, Sequence[str], None] = 'e27aafd466ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('workout_location', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_workout_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('workout_days_per_week', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_workout_split', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'preferred_workout_split')
    op.drop_column('user_profiles', 'workout_days_per_week')
    op.drop_column('user_profiles', 'preferred_workout_duration_minutes')
    op.drop_column('user_profiles', 'workout_location')
    op.drop_column('user_profiles', 'bmi')
    # ### end Alembic commands ###
