"""add exercise table

Revision ID: c19d05954fa8
Revises: b785c678f512
Create Date: 2026-07-14 21:15:34.524871

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19d05954fa8'
down_revision: Union[str, Sequence[str], None] = 'b785c678f512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('exercise_type', sa.String(length=100), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=False),
    sa.Column('equipment', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('knowledge_document', sa.Text(), nullable=False),
    sa.Column('embedding', VECTOR(dim=768), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_body_part'), 'exercises', ['body_part'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_title'), 'exercises', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_title'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_body_part'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
